import { test } from 'node:test';
import assert from 'node:assert/strict';
import { buildScenes, chooseLocally, createProject, escapeXml, selectTemplate, subtitles, timecode } from '../server/engine';
import { briefSchema, updateSchema, uuidSchema } from '../server/schema';
import { dimensions, sceneSvg } from '../server/render';
import { sampleBrief } from '../shared/types';

test('15/30/45/60 秒编排保持总时长且卖点进入独立分镜',()=>{for(const duration of [15,30,45,60]){const scenes=buildScenes({...sampleBrief,duration},'editorial',[]);assert.equal(scenes.reduce((n,s)=>n+s.duration,0),duration);assert.equal(scenes.length,5);assert.ok(scenes.every(s=>s.duration>=1));assert.equal(scenes[1]!.caption,'温润哑光釉面');assert.equal(scenes.at(-1)!.caption,sampleBrief.cta);assert.equal(new Set(scenes.map(s=>s.id)).size,5);}});
test('不同模板与显式选择执行不同内容结构',()=>{assert.equal(chooseLocally({...sampleBrief,template:'auto',style:'科技性能对比'}),'benefits');assert.equal(chooseLocally({...sampleBrief,template:'auto',style:'一个下班后的故事'}),'story');assert.equal(chooseLocally({...sampleBrief,template:'editorial',style:'科技性能'}),'editorial');assert.match(buildScenes(sampleBrief,'benefits',[])[0]!.caption,/而来$/);assert.match(buildScenes(sampleBrief,'story',[])[0]!.caption,/今天/);});
test('显式模板不会调用 Jev，返回真实引擎标记',async()=>{const result=await selectTemplate({...sampleBrief,template:'story'},[]);assert.equal(result.engine,'local');assert.equal(result.confidence,null);assert.equal(result.template,'story');});
test('SRT 时间轴连续且毫秒正确',()=>{const scenes=buildScenes(sampleBrief,'editorial',[]);scenes[0]!.duration=1.5;scenes[1]!.duration=2.75;const result=subtitles(scenes);assert.match(result,/00:00:00,000 --> 00:00:01,500/);assert.match(result,/00:00:01,500 --> 00:00:04,250/);assert.equal(timecode(3661.125),'01:01:01,125');});
test('不接受不完整brief、非法比例、失控总时长及重复镜头id',()=>{assert.equal(briefSchema.safeParse({...sampleBrief,product:''}).success,false);assert.equal(briefSchema.safeParse({...sampleBrief,benefits:'长'.repeat(161)}).success,false);assert.equal(briefSchema.safeParse({...sampleBrief,ratio:'2:1'}).success,false);assert.equal(briefSchema.safeParse({...sampleBrief,duration:3600}).success,false);const scenes=buildScenes(sampleBrief,'editorial',[]);assert.equal(updateSchema.safeParse({name:'x',revision:1,scenes:scenes.map(s=>({...s,duration:30}))}).success,false);assert.equal(updateSchema.safeParse({name:'x',revision:1,scenes:[scenes[0],scenes[0]]}).success,false);assert.equal(uuidSchema.safeParse('../../.env').success,false);});
test('所有文本在SVG中转义，字幕不能注入标签',()=>{assert.equal(escapeXml('<script>"&'), '&lt;script&gt;&quot;&amp;');const project=createProject(sampleBrief,{engine:'local',template:'editorial',message:'test',confidence:null});const scene={...project.scenes[0]!,caption:'<svg onload="evil()">'};const output=sceneSvg(project,scene,0,1280,720);assert.ok(!output.includes('<svg onload='));assert.ok(output.includes('&lt;svg'));assert.deepEqual(dimensions('9:16'),[720,1280]);});

test('长字幕保持完整并自动缩小字级，而非截断',()=>{const project=createProject(sampleBrief,{engine:'local',template:'editorial',message:'test',confidence:null});const scene={...project.scenes[0]!,caption:'字'.repeat(150)+'结尾保留'};const output=sceneSvg(project,scene,0,1280,720);assert.equal((output.match(/字/g)||[]).length,150);assert.ok(output.includes('结尾保留'));});
