import 'dotenv/config';
import express from 'express';
import multer from 'multer';
import sharp from 'sharp';
import path from 'node:path';
import fs from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
import { z } from 'zod';
import { briefSchema, updateSchema } from './schema';
import { createProject, script, selectTemplate, subtitles } from './engine';
import { ASSET_DIR, EXPORT_DIR, initStore, listProjects, readProject, safeId, saveProject, withProjectLock } from './store';
import { enqueueRender, ffmpegAvailable, jobs, renderFrame, restoreJobs } from './render';
import type { Asset } from '../shared/types';

async function builtInAssets():Promise<Asset[]>{const id='5d32b3b6-1f4d-4b8f-9a83-c43a0f4ff9a2';const dest=path.join(ASSET_DIR,`${id}.jpg`);try{const file=await sharp(path.resolve('public/media/ceramic-cup.png')).resize(2560,2560,{fit:'inside',withoutEnlargement:true}).jpeg({quality:90}).toBuffer({resolveWithObject:true});await fs.writeFile(dest,file.data,{mode:0o600});return [{id,name:'晨间陶杯 · 内置示例素材',url:`/api/assets/${id}`,width:file.info.width,height:file.info.height,size:file.data.length,createdAt:new Date().toISOString()}];}catch{return [];}}
const app=express();app.disable('x-powered-by');const port=Number(process.env.PORT||4311);const host=process.env.HOST||'127.0.0.1';
app.use((req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('X-Frame-Options','DENY');if(!['127.0.0.1','localhost','[::1]','::1'].includes(req.hostname))return res.status(403).json({error:'此工作室仅接受本机主机名访问'});const origin=req.headers.origin;if(origin&&origin!==`http://${req.headers.host}`&&origin!==`https://${req.headers.host}`)return res.status(403).json({error:'不允许跨站请求'});next();});
app.use(express.json({limit:'64kb'}));
const limiter=new Map<string,{count:number;until:number}>();
app.use('/api',(req,res,next)=>{const now=Date.now();for(const[k,v]of limiter)if(v.until<now)limiter.delete(k);const key=req.ip||'local';const data=limiter.get(key)||{count:0,until:now+60000};data.count++;limiter.set(key,data);if(data.count>180)return res.status(429).json({error:'请求过于频繁，请稍后再试'});next();});
app.get('/api/health',async(_req,res)=>res.json({ok:true,jevConfigured:Boolean(process.env.TYPESAFE_API_KEY),ffmpeg:await ffmpegAvailable(),version:'0.1.0',storage:'local'}));
app.get('/api/projects',async(_req,res)=>res.json(await listProjects()));
app.post('/api/projects',async(req,res)=>{const brief=briefSchema.parse(req.body);const assets=brief.product==='晨间陶杯'?await builtInAssets():[];const decision=await selectTemplate(brief,assets);const project=createProject(brief,decision,assets);await saveProject(project);res.status(201).json(project);});
app.get('/api/projects/:id',async(req,res)=>res.json(await readProject(safeId(req.params.id))));
app.put('/api/projects/:id',async(req,res)=>{const id=safeId(req.params.id);const input=updateSchema.parse(req.body);const project=await withProjectLock(id,async()=>{const current=await readProject(id);if(current.revision!==input.revision)throw Object.assign(new Error('项目已在其他窗口更新，请重新打开后编辑'),{status:409});if(input.scenes.some(s=>s.assetId&&!current.assets.some(a=>a.id===s.assetId)))throw Object.assign(new Error('分镜包含不属于该项目的素材'),{status:400});Object.assign(current,{name:input.name,scenes:input.scenes,revision:current.revision+1,updatedAt:new Date().toISOString()});await saveProject(current);return current;});res.json(project);});
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:12*1024*1024,files:1},fileFilter:(_req,file,cb)=>{if(!['image/jpeg','image/png','image/webp'].includes(file.mimetype))return cb(Object.assign(new Error('仅支持 JPG、PNG、WebP 图片'),{status:400}));cb(null,true);}});
app.post('/api/projects/:id/assets',upload.single('file'),async(req,res)=>{const id=safeId(req.params.id);if(!req.file)return res.status(400).json({error:'请选择图片文件'});const file=req.file;const result=await withProjectLock(id,async()=>{const project=await readProject(id);if(project.assets.length>=24)throw Object.assign(new Error('每个项目最多 24 张素材'),{status:400});const metadata=await sharp(file.buffer,{limitInputPixels:40_000_000}).metadata();if(!['jpeg','png','webp'].includes(metadata.format||''))throw Object.assign(new Error('无效的图片格式'),{status:400});const assetId=randomUUID();const encoded=await sharp(file.buffer,{limitInputPixels:40_000_000}).rotate().resize(2560,2560,{fit:'inside',withoutEnlargement:true}).jpeg({quality:88}).toBuffer({resolveWithObject:true});await fs.writeFile(path.join(ASSET_DIR,`${assetId}.jpg`),encoded.data,{mode:0o600});const asset:Asset={id:assetId,name:file.originalname.slice(0,160),url:`/api/assets/${assetId}`,width:encoded.info.width,height:encoded.info.height,size:encoded.data.length,createdAt:new Date().toISOString()};project.assets.push(asset);project.revision++;project.updatedAt=new Date().toISOString();await saveProject(project);return {project,asset};});res.status(201).json(result);});
app.get('/api/assets/:id',async(req,res)=>res.sendFile(path.join(ASSET_DIR,`${safeId(req.params.id)}.jpg`),{dotfiles:'allow'}));
app.get('/api/projects/:id/scenes/:sceneId/preview',async(req,res)=>{const project=await readProject(safeId(req.params.id));const index=project.scenes.findIndex(s=>s.id===safeId(req.params.sceneId));if(index<0)return res.status(404).json({error:'分镜不存在'});const ratio=project.brief.ratio;const [w,h]=ratio==='9:16'?[360,640]:ratio==='1:1'?[480,480]:[640,360];const frame=await renderFrame(project,project.scenes[index]!,index,w!,h!);res.setHeader('Cache-Control','private, max-age=0');res.type('jpg').send(frame);});
app.get('/api/projects/:id/download/:kind',async(req,res)=>{const project=await readProject(safeId(req.params.id));const kind=z.enum(['script','subtitles','project']).parse(req.params.kind);const data=kind==='script'?script(project):kind==='subtitles'?subtitles(project.scenes):JSON.stringify(project,null,2);res.attachment(kind==='script'?'script.md':kind==='subtitles'?'captions.srt':'project.json').send(data);});
app.post('/api/projects/:id/render',async(req,res)=>{const project=await readProject(safeId(req.params.id));res.status(202).json(await enqueueRender(project));});
app.get('/api/projects/:id/exports',async(req,res)=>{const id=safeId(req.params.id);await readProject(id);res.json([...jobs.values()].filter(j=>j.projectId===id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)));});
app.get('/api/jobs/:id',(req,res)=>{const job=jobs.get(safeId(req.params.id));if(!job)return res.status(404).json({error:'任务不存在'});res.json(job);});
app.get('/api/exports/:id/:file',(req,res)=>{const id=safeId(req.params.id);const filename=z.enum(['video.mp4','delivery.zip','cover.jpg']).parse(req.params.file);const job=jobs.get(id);if(!job||job.status!=='complete')return res.status(404).json({error:'成品尚未就绪'});if(filename==='delivery.zip')res.attachment('xtasy-delivery.zip');res.sendFile(path.join(EXPORT_DIR,id,filename),{dotfiles:'allow'});});
await initStore();await restoreJobs();
app.use('/api',(_req,res)=>res.status(404).json({error:'接口不存在'}));
app.use((error:unknown,_req:express.Request,res:express.Response,_next:express.NextFunction)=>{if(error instanceof z.ZodError)return res.status(400).json({error:error.issues.map(i=>i.message).join('；')});if(error instanceof multer.MulterError)return res.status(400).json({error:error.code==='LIMIT_FILE_SIZE'?'图片不能超过 12 MB':'上传数量超出限制'});const err=error as Error&{status?:number;code?:string};if(err.code==='ENOENT')return res.status(404).json({error:'项目或文件不存在'});const status=err.status||500;res.status(status).json({error:status<500?err.message:'处理失败，请稍后重试。如持续失败，请检查本地存储权限。'});});
if(process.env.NODE_ENV==='production'||path.basename(path.dirname(process.argv[1]||''))==='dist-server'){app.use(express.static(path.resolve('dist')));app.get('/{*splat}',(_req,res)=>res.sendFile(path.resolve('dist/index.html')));}else{const{createServer}=await import('vite');const vite=await createServer({server:{middlewareMode:true},appType:'spa'});app.use(vite.middlewares);}
app.listen(port,host,()=>console.log(`Xtasy Director ready: http://${host}:${port}`));
