import fs from 'node:fs/promises';
import path from 'node:path';
import { createWriteStream } from 'node:fs';
import { spawn } from 'node:child_process';
import { randomUUID } from 'node:crypto';
import sharp from 'sharp';
import archiver from 'archiver';
import type { Project, RenderJob, Scene } from '../shared/types';
import { ASSET_DIR, EXPORT_DIR, safeId } from './store';
import { escapeXml, script, subtitles } from './engine';

export function runBinary(binary:string,args:string[],timeoutMs=180000):Promise<void>{return new Promise((resolve,reject)=>{const child=spawn(binary,args,{stdio:['ignore','ignore','pipe'],shell:false});let stderr='';const timer=setTimeout(()=>{child.kill('SIGKILL');reject(new Error('渲染超时，请缩短时长后重试'));},timeoutMs);child.stderr.on('data',(chunk:Buffer)=>{stderr=(stderr+chunk.toString()).slice(-4000);});child.on('error',error=>{clearTimeout(timer);reject(error);});child.on('close',code=>{clearTimeout(timer);if(code===0)resolve();else reject(new Error(`视频编码失败 (${code})：${stderr.slice(-400)}`));});});}
export async function ffmpegAvailable():Promise<boolean>{try{await runBinary(process.env.FFMPEG_PATH||'ffmpeg',['-version'],5000);return true;}catch{return false;}}
const wrap=(text:string,maxWidth:number)=>{const result:string[]=[];let current='',width=0;for(const c of text){const w=/[\x00-\xff]/.test(c)?0.55:1;if(width+w>maxWidth){result.push(current);current='';width=0;}current+=c;width+=w;}if(current)result.push(current);return result;};
export function sceneSvg(project:Project,scene:Scene,index:number,width:number,height:number,hasImage=false):string {
 const portrait=height>width;const pad=Math.round(width*.064);let font=Math.round(width*(portrait?.064:.047));let captionLines=wrap(scene.caption,(width-pad*2)/font);while(captionLines.length*font*1.4>height*.5&&font>14){font-=2;captionLines=wrap(scene.caption,(width-pad*2)/font);}const bottom=Math.round(height*.81);const template=project.decision.template;const colors=template==='benefits'?['#d4ddcc','#798c6e','#eaf0e3']:template==='story'?['#d8d8e5','#79798d','#efedf5']:['#e8dcc9','#a28b70','#f7f1e6'];
 const image=hasImage?`<rect width="${width}" height="${height}" fill="url(#shade)"/>`:`<rect width="${width}" height="${height}" fill="${colors[0]}"/><circle cx="${width*.8}" cy="${height*.3}" r="${width*.5}" fill="${colors[2]}" opacity=".68"/><path d="M 0 ${height*.62} L ${width} ${height*.38} L ${width} ${height} L 0 ${height}Z" fill="${colors[1]}" opacity=".2"/><g transform="translate(${width*(portrait?.12:.44)} ${height*(portrait?.19:.12)}) scale(${Math.min(width/750,height/600)})"><ellipse cx="240" cy="370" rx="180" ry="30" fill="#443628" opacity=".16"/><path d="M 100 130 C 100 105 370 105 370 130 L 345 325 Q 235 388 125 325Z" fill="url(#cup)"/><ellipse cx="235" cy="129" rx="135" ry="35" fill="#faf6ed"/><ellipse cx="235" cy="133" rx="113" ry="23" fill="#756047"/><path d="M 363 175 C 490 145 455 315 350 280" fill="none" stroke="#eee8db" stroke-width="33"/><path d="M 141 156 L 156 303" stroke="#fff" stroke-width="11" opacity=".35"/><path d="M 210 85 C 186 56 240 45 213 12 M 266 82 C 240 50 291 40 272 0" fill="none" stroke="#fff" opacity=".38" stroke-width="6" stroke-linecap="round"/></g>`;
 return `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}"><defs><linearGradient id="cup"><stop stop-color="#e1d8c7"/><stop offset=".42" stop-color="#fffcf3"/><stop offset="1" stop-color="#d0c3ad"/></linearGradient><linearGradient id="shade" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#000" stop-opacity=".08"/><stop offset=".48" stop-color="#000" stop-opacity="0"/><stop offset="1" stop-color="#000" stop-opacity=".8"/></linearGradient></defs>${image}<g fill="${hasImage?'#fff':'#332b22'}" font-family="PingFang SC,Noto Sans CJK SC,Microsoft YaHei,sans-serif"><text x="${pad}" y="${pad+12}" font-size="${Math.round(width*.018)}" letter-spacing="3">XTASY / DIRECTOR</text>${hasImage?'':`<text x="${pad}" y="${pad+38}" font-size="${Math.round(width*.016)}" opacity=".6">示意画面 · 上传产品图片后替换</text>`}<text x="${width-pad}" y="${pad+12}" text-anchor="end" font-size="${Math.round(width*.02)}">${String(index+1).padStart(2,'0')}</text>${captionLines.map((line,i)=>`<text x="${pad}" y="${bottom-(captionLines.length-1-i)*font*1.4}" font-size="${font}" font-weight="600">${escapeXml(line)}</text>`).join('')}<text x="${pad}" y="${height-pad}" font-size="${Math.round(width*.018)}" opacity=".75">${escapeXml(project.brief.product.slice(0,40))}  /  ${escapeXml(scene.title)}</text></g></svg>`;
}
export function dimensions(ratio:string):[number,number]{return ratio==='9:16'?[720,1280]:ratio==='1:1'?[960,960]:[1280,720];}
export async function renderFrame(project:Project,scene:Scene,index:number,width:number,height:number):Promise<Buffer>{const asset=project.assets.find(a=>a.id===scene.assetId);if(asset){const base=await sharp(path.join(ASSET_DIR,`${safeId(asset.id)}.jpg`),{limitInputPixels:40_000_000}).resize(width,height,{fit:'cover'}).toBuffer();return sharp(base).composite([{input:Buffer.from(sceneSvg(project,scene,index,width,height,true))}]).jpeg({quality:90}).toBuffer();}return sharp(Buffer.from(sceneSvg(project,scene,index,width,height))).jpeg({quality:90}).toBuffer();}
export const jobs=new Map<string,RenderJob>();let active=false;let reserving=false;const queue:{job:RenderJob;project:Project}[]=[];
async function persist(job:RenderJob):Promise<void>{await fs.writeFile(path.join(EXPORT_DIR,job.id,'job.json'),JSON.stringify(job,null,2));}
export async function restoreJobs():Promise<void>{const dirs=await fs.readdir(EXPORT_DIR);await Promise.all(dirs.map(async dir=>{if(!/^[0-9a-f-]{36}$/.test(dir))return;try{const job=JSON.parse(await fs.readFile(path.join(EXPORT_DIR,dir,'job.json'),'utf8')) as RenderJob;if(job.status==='rendering'||job.status==='queued'){job.status='failed';job.error='服务重启导致任务中断，请重新导出';job.stage='任务中断';await persist(job);}jobs.set(job.id,job);}catch{/* Incomplete export folders are ignored; no completed artifact is reported. */}}));}
export async function enqueueRender(project:Project):Promise<RenderJob>{
 if(active||reserving||queue.length)throw Object.assign(new Error('已有视频正在渲染，请完成后再试'),{status:429});
 reserving=true;
 try{
  if(!(await ffmpegAvailable()))throw Object.assign(new Error('未找到 FFmpeg。请按 README 安装后重试；制作脚本和字幕仍可单独下载。'),{status:503});
  const job:RenderJob={id:randomUUID(),projectId:project.id,revision:project.revision,status:'queued',stage:'准备制作文件',completedScenes:0,totalScenes:project.scenes.length,createdAt:new Date().toISOString()};
  await fs.mkdir(path.join(EXPORT_DIR,job.id),{recursive:true});jobs.set(job.id,job);await persist(job);queue.push({job,project:structuredClone(project)});void consume();return job;
 }finally{reserving=false;}
}

async function consume():Promise<void>{if(active)return;const next=queue.shift();if(!next)return;active=true;const{job,project}=next;const dir=path.join(EXPORT_DIR,job.id);try{job.status='rendering';job.stage='制作分镜画面';await persist(job);const [width,height]=dimensions(project.brief.ratio);for(let i=0;i<project.scenes.length;i++){const frame=await renderFrame(project,project.scenes[i]!,i,width,height);await fs.writeFile(path.join(dir,`scene-${i}.jpg`),frame);job.completedScenes=i+1;await persist(job);}await fs.writeFile(path.join(dir,'cover.svg'),sceneSvg(project,project.scenes[0]!,0,width,height));await fs.copyFile(path.join(dir,'scene-0.jpg'),path.join(dir,'cover.jpg'));await fs.writeFile(path.join(dir,'script.md'),script(project));await fs.writeFile(path.join(dir,'captions.srt'),subtitles(project.scenes));await fs.writeFile(path.join(dir,'project.json'),JSON.stringify(project,null,2));await fs.writeFile(path.join(dir,'README.txt'),'Xtasy Director 成品包\n\nvideo.mp4：含轻微推近动效与画面字幕的分镜预览，无配音。\ncover.jpg：实际首镜封面。cover.svg：可编辑排版底稿（通用产品示意图，不包含上传图片）。\nscript.md：可供拍摄或视频生成服务执行的镜头脚本。\ncaptions.srt：标准字幕。project.json：完整项目结构。\nscene-*.jpg：每个分镜画面。\n\n商品参数由用户提供，请在发布前核对。上传素材仅保存在运行此应用的机器。\n');const concat=project.scenes.map((s,i)=>`file 'scene-${i}.jpg'\nduration ${s.duration}`).join('\n')+`\nfile 'scene-${project.scenes.length-1}.jpg'\n`;await fs.writeFile(path.join(dir,'frames.txt'),concat);job.stage='FFmpeg 编码 MP4';await persist(job);await runBinary(process.env.FFMPEG_PATH||'ffmpeg',['-y','-hide_banner','-loglevel','error','-f','concat','-safe','1','-i',path.join(dir,'frames.txt'),'-vf',`fps=24,zoompan=z='min(zoom+0.00006,1.035)':d=1:s=${width}x${height}:fps=24,format=yuv420p`,'-c:v','libx264','-preset','veryfast','-crf','23','-threads','2','-t',String(project.scenes.reduce((n,s)=>n+s.duration,0)),'-movflags','+faststart',path.join(dir,'video.mp4')]);job.stage='打包交付文件';await persist(job);await new Promise<void>((resolve,reject)=>{const output=createWriteStream(path.join(dir,'delivery.zip'));const archive=archiver('zip',{zlib:{level:5}});output.on('close',resolve);output.on('error',reject);archive.on('error',reject);archive.pipe(output);for(const file of ['video.mp4','cover.jpg','cover.svg','script.md','captions.srt','project.json','README.txt',...project.scenes.map((_,i)=>`scene-${i}.jpg`)])archive.file(path.join(dir,file),{name:file});void archive.finalize();});job.status='complete';job.stage='成品包已就绪';job.videoUrl=`/api/exports/${job.id}/video.mp4`;job.packageUrl=`/api/exports/${job.id}/delivery.zip`;job.coverUrl=`/api/exports/${job.id}/cover.jpg`;await persist(job);}catch(error){job.status='failed';job.stage='导出失败';job.error=error instanceof Error?error.message:'未知导出错误';await persist(job);}finally{active=false;void consume();}}
