import { useEffect, useRef, useState } from 'react';
import { ArrowDownToLine, ArrowLeft, ArrowRight, Check, CheckCheck, ChevronDown, Clapperboard, Clock3, Film, FolderOpen, ImagePlus, Layers3, LoaderCircle, Maximize, MoreHorizontal, Play, Plus, Save, Settings2, Sparkles, WandSparkles, X } from 'lucide-react';
import { sampleBrief, templates } from '../shared/types';
import type { Brief, Project, ProjectSummary, RenderJob, Scene, TemplateId } from '../shared/types';

type View='studio'|'projects'|'templates'|'settings';type Stage='brief'|'storyboard'|'delivery';
interface Health{jevConfigured:boolean;ffmpeg:boolean;version:string}
async function api<T>(url:string,options?:RequestInit):Promise<T>{const response=await fetch(url,{...options,headers:options?.body instanceof FormData?options.headers:{'Content-Type':'application/json',...options?.headers}});const data=await response.json();if(!response.ok)throw new Error(data.error||'请求失败，请重试');return data as T;}
const duration=(scenes:Scene[])=>scenes.reduce((total,scene)=>total+scene.duration,0);
const formatDate=(value:string)=>new Intl.DateTimeFormat('zh-CN',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(value));
const shotUrl=(p:Project,s:Scene)=>`/api/projects/${p.id}/scenes/${s.id}/preview?v=${p.revision}`;
function Mark(){return <span className="brand-mark"><span/><span/><span/></span>;}

export default function App(){
 const[view,setView]=useState<View>('studio');const[stage,setStage]=useState<Stage>('brief');const[brief,setBrief]=useState<Brief>({...sampleBrief});const[health,setHealth]=useState<Health|null>(null);const[projects,setProjects]=useState<ProjectSummary[]>([]);const[project,setProject]=useState<Project|null>(null);const[scenes,setScenes]=useState<Scene[]>([]);const[selected,setSelected]=useState(0);const[busy,setBusy]=useState('');const[error,setError]=useState('');const[notice,setNotice]=useState('');const[job,setJob]=useState<RenderJob|null>(null);const[exports,setExports]=useState<RenderJob[]>([]);const[isPlaying,setIsPlaying]=useState(false);const[search,setSearch]=useState('');const busyRef=useRef(false);const uploadRef=useRef<HTMLInputElement>(null);const mainRef=useRef<HTMLElement>(null);
 const dirty=Boolean(project&&JSON.stringify(project.scenes)!==JSON.stringify(scenes));const activeScene=scenes[selected];
 const refresh=async()=>setProjects(await api<ProjectSummary[]>('/api/projects'));
 useEffect(()=>{void Promise.all([api<Health>('/api/health').then(setHealth),refresh()]).catch(e=>setError(e.message));},[]);
 useEffect(()=>{if(!dirty)return;const handler=(e:BeforeUnloadEvent)=>{e.preventDefault();};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler);},[dirty]);
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),4000);return()=>clearTimeout(timer);},[notice]);
 useEffect(()=>{if(!isPlaying||!activeScene)return;const timer=setTimeout(()=>{if(selected>=scenes.length-1){setIsPlaying(false);setSelected(0);}else setSelected(i=>i+1);},activeScene.duration*1000);return()=>clearTimeout(timer);},[isPlaying,selected,activeScene,scenes.length]);
 useEffect(()=>{if(!job||!['queued','rendering'].includes(job.status))return;let canceled=false;let attempts=0;const timer=setInterval(()=>{attempts++;if(attempts>240){clearInterval(timer);setError('渲染查询已暂停。请重新打开项目查看任务状态。');return;}void api<RenderJob>(`/api/jobs/${job.id}`).then(next=>{if(!canceled){setJob(next);if(next.status==='complete')setNotice('视频与成品包已生成');}}).catch(e=>{if(!canceled)setError(e.message);clearInterval(timer);});},1000);return()=>{canceled=true;clearInterval(timer);};},[job?.id,job?.status]);
 const act=async(label:string,action:()=>Promise<void>)=>{if(busyRef.current)return;busyRef.current=true;setBusy(label);setError('');try{await action();}catch(e){setError(e instanceof Error?e.message:'操作失败，请重试');}finally{busyRef.current=false;setBusy('');}};
 const newProject=()=>{if(busyRef.current)return;const reset=()=>{setProject(null);setScenes([]);setStage('brief');setView('studio');setJob(null);setExports([]);setBrief({...sampleBrief});setSelected(0);};if(dirty)void act('正在保存',async()=>{await save();reset();});else reset();};
 const openProject=async(id:string)=>{await act('正在打开',async()=>{if(dirty)await save();const p=await api<Project>(`/api/projects/${id}`);setProject(p);setScenes(p.scenes);setBrief(p.brief);setSelected(0);setIsPlaying(false);setView('studio');setStage('storyboard');const list=await api<RenderJob[]>(`/api/projects/${id}/exports`);setExports(list);setJob(list[0]??null);});};
 const save=async():Promise<Project>=>{if(!project)throw new Error('请先生成分镜');if(!dirty)return project;const p=await api<Project>(`/api/projects/${project.id}`,{method:'PUT',body:JSON.stringify({revision:project.revision,name:project.name,scenes})});setProject(p);setScenes(p.scenes);return p;};
 const generate=async()=>{await act('正在编排分镜',async()=>{const p=await api<Project>('/api/projects',{method:'POST',body:JSON.stringify(brief)});setProject(p);setScenes(p.scenes);setSelected(0);setStage('storyboard');setJob(null);setExports([]);setNotice('分镜已保存，开始打磨你的短片');await refresh();});};
 const updateScene=(patch:Partial<Scene>)=>{if(busyRef.current)return;setScenes(list=>list.map((s,i)=>i===selected?{...s,...patch}:s));};
 const render=async()=>{await act('正在提交导出',async()=>{setIsPlaying(false);const p=await save();const next=await api<RenderJob>(`/api/projects/${p.id}/render`,{method:'POST'});setJob(next);setStage('delivery');setExports(list=>[next,...list]);});};
 const upload=async(file:File)=>{await act('正在保存素材',async()=>{const p=await save();const form=new FormData();form.append('file',file);const result=await api<{project:Project;asset:{id:string}}>(`/api/projects/${p.id}/assets`,{method:'POST',body:form});const updated=result.project;setProject(updated);setScenes(updated.scenes);const nextScenes=updated.scenes.map((s,i)=>i===selected?{...s,assetId:result.asset.id}:s);const final=await api<Project>(`/api/projects/${p.id}`,{method:'PUT',body:JSON.stringify({revision:updated.revision,name:updated.name,scenes:nextScenes})});setProject(final);setScenes(final.scenes);setNotice('已上传并应用到当前分镜');});};
 const selectTemplate=(id:TemplateId)=>{if(busyRef.current)return;setBrief(b=>({...b,template:id}));setStage('brief');setView('studio');};
 const go=(target:View)=>{if(busyRef.current)return;setView(target);setIsPlaying(false);if(target==='projects')void refresh();};
 const btnBusy=busy!=='';const rendering=job?.status==='rendering'||job?.status==='queued';
 return <><div className="app-shell" inert={btnBusy||undefined} aria-busy={btnBusy}>
  <aside className="sidebar">
   <a href="#" className="brand" onClick={e=>{e.preventDefault();go('studio');}}><Mark/><span>xtasy<span className="brand-product">DIRECTOR</span></span></a>
   <div className="workspace"><div className="workspace-icon">S</div><div><b>我的创作空间</b><span>Local studio</span></div><ChevronDown size={14}/></div>
   <div className="nav-label">工作空间</div><nav aria-label="主导航">
    <button className={view==='studio'?'active':''} onClick={()=>go('studio')}><Clapperboard size={18}/>导演工作台<span className="nav-dot"/></button>
    <button className={view==='projects'?'active':''} onClick={()=>go('projects')}><FolderOpen size={18}/>我的项目<span className="nav-count">{projects.length}</span></button>
    <button className={view==='templates'?'active':''} onClick={()=>go('templates')}><Layers3 size={18}/>内容模板<span className="nav-count">3</span></button>
   </nav>
   <div className="sidebar-note"><span className="small-spark">✳</span><h3>好的故事，<br/>从一个想法开始。</h3><p>把想法带进来，<br/>把下一支短片带出去。</p><button onClick={newProject}><Plus size={14}/>新建项目</button></div>
   <div className="sidebar-bottom"><button onClick={()=>go('settings')} className={view==='settings'?'active':''}><Settings2 size={17}/>工作室设置</button><div className="profile"><span>创</span><div><b>独立创作者</b><small>本地工作空间 · v0.1</small></div><span className="online"/></div></div>
  </aside>
  <div className="main-shell">
   <header className="topbar"><div className="breadcrumb">工作空间<span>/</span><b>{{studio:'导演工作台',projects:'我的项目',templates:'内容模板',settings:'工作室设置'}[view]}</b></div><div className="topbar-actions"><span className="status"><i/>{health?.jevConfigured?'Jev 已配置':'本地模板引擎'}</span><a href="https://docs.typesafe.ai/concepts/system-one" target="_blank" rel="noreferrer" className="help-link">了解 Jev ↗</a></div></header>
   <main ref={mainRef}>
   {error&&<div role="alert" className="alert error"><span>{error}</span><button aria-label="关闭错误" onClick={()=>setError('')}><X size={16}/></button></div>}
   {notice&&<div role="status" className="toast"><Check size={16}/>{notice}</div>}
   {view==='studio'&&<>
    <div className="page-heading"><div><div className="eyebrow">YOUR NEXT GREAT STORY</div><h1>{project?project.name:'让想法，成为下一支短片。'}</h1><p>{project?'从镜头到成片，每一步都在你的掌控之中。':'从一份简报出发，完成分镜、视频和发布素材。'}</p></div>{project&&<button className="button ghost" onClick={newProject}><Plus size={16}/>新建项目</button>}</div>
    <div className="stepper" aria-label="制作流程">{(['brief','storyboard','delivery']as Stage[]).map((step,i)=><button key={step} className={stage===step?'current':project&&i===0?'done':''} disabled={!project&&i>0} onClick={()=>{setStage(step);setIsPlaying(false);}}><span className="step-num">{project&&i===0?<Check size={14}/>:String(i+1).padStart(2,'0')}</span><div><b>{['创作简报','分镜工作台','成品交付'][i]}</b><small>{['THE BRIEF','STORYBOARD','DELIVERY'][i]}</small></div>{i<2&&<ArrowRight size={15} className="step-arrow"/>}</button>)}<span className="stepper-note">{project?`项目已保存 · ${formatDate(project.updatedAt)}`:'你的创意，已经就位。'}</span></div>
    {stage==='brief'&&<>
     <div className="brief-grid"><section className="panel brief-panel"><div className="section-top"><div><span className="section-index">01 / </span><h2>写下你的创作简报</h2></div><span className="chip">约 1 分钟</span></div><p className="section-copy">越具体的想法，越贴近你想要的表达。</p>
      <form onSubmit={e=>{e.preventDefault();void generate();}}>
       <label className="field"><span>产品 / 品牌名称 <i>*</i></span><input required maxLength={80} value={brief.product} onChange={e=>setBrief({...brief,product:e.target.value})} placeholder="例如：晨间陶杯"/></label>
       <label className="field"><span>写给谁看 <i>*</i></span><input required maxLength={300} value={brief.audience} onChange={e=>setBrief({...brief,audience:e.target.value})} placeholder="描述目标受众"/></label>
       <label className="field"><span>最想表达的卖点 <i>*</i><small>一行一个，最多采用前三条</small></span><textarea required maxLength={1000} rows={3} value={brief.benefits} onChange={e=>setBrief({...brief,benefits:e.target.value})}/></label>
       <label className="field"><span>表达风格</span><input maxLength={300} value={brief.style} onChange={e=>setBrief({...brief,style:e.target.value})}/></label>
       <div className="form-row"><label className="field"><span>短片时长</span><select value={brief.duration} onChange={e=>setBrief({...brief,duration:Number(e.target.value)})}>{[15,30,45,60].map(n=><option key={n} value={n}>{n} 秒</option>)}</select></label><label className="field"><span>画面比例</span><select value={brief.ratio} onChange={e=>setBrief({...brief,ratio:e.target.value as Brief['ratio']})}><option>16:9</option><option>9:16</option><option>1:1</option></select></label></div>
       <label className="field"><span>收尾 / 行动文案 <i>*</i></span><input required maxLength={100} value={brief.cta} onChange={e=>setBrief({...brief,cta:e.target.value})}/></label>
       <div className="brief-bottom"><span><Sparkles size={14}/>{brief.template==='auto'?'让 Jev 为你匹配内容结构':templates.find(t=>t.id===brief.template)?.name}</span><button type="submit" disabled={btnBusy} className="button primary">{btnBusy?<LoaderCircle className="spin" size={17}/>:<WandSparkles size={17}/>} {busy||'生成分镜'}<ArrowRight size={16}/></button></div>
      </form>
     </section><section className="inspiration"><div className="inspiration-top"><span>THE EVERYDAY COLLECTION</span><span>VOL. 01</span></div><div className="inspiration-image"><img src="/media/ceramic-cup.png" alt="自然光下的晨间陶杯，内置示例素材" onError={e=>{e.currentTarget.src='/demo-product.svg';}}/><span className="image-tag"><span/>内置示例素材</span><div className="image-caption"><span>A MOMENT, MADE YOURS.</span><h2>给日常，<br/>留一点温度。</h2><div><span className="line"/>晨间陶杯 · 15 秒品牌短片</div></div></div><div className="inspiration-footer"><div><span className="mini-icon"><Clapperboard size={18}/></span><span><b>从第一个镜头，到完整交付。</b><small>视频 · 字幕 · 封面 · 制作脚本</small></span></div><ArrowRight size={20}/></div><p className="honest-note">Jev 负责选择内容结构，模板引擎编排脚本。导出包含图片动效视频；你可以上传自己的产品素材。</p></section></div>
     <div className="templates-heading"><div><h2>每一个好故事，都有自己的节奏。</h2><p>选一个起点，或把选择交给 Jev。</p></div><button className={`auto-select ${brief.template==='auto'?'selected':''}`} onClick={()=>setBrief({...brief,template:'auto'})}><Sparkles size={14}/>{brief.template==='auto'?'Jev 自动匹配已选':'让 Jev 自动匹配'}</button></div>
     <div className="template-row">{templates.map((t,i)=><button key={t.id} onClick={()=>setBrief({...brief,template:t.id})} className={`template-card ${brief.template===t.id?'chosen':''}`}><span className={`template-art art-${i}`}><span className="abstract-circle"/><span className="abstract-block"/><span className="art-index">0{i+1}</span></span><span className="template-copy"><small>{t.english}</small><b>{t.name}</b><span>{t.tag}</span></span><span className="template-check">{brief.template===t.id?<Check size={14}/>:<ArrowUpRight/>}</span></button>)}</div>
    </>}
    {stage==='storyboard'&&project&&<>
     <div className="board-toolbar"><div><h2>分镜工作台</h2><span>{scenes.length} 个镜头 <i/> {duration(scenes)} 秒 <i/> {project.brief.ratio}</span></div><div><button className="button ghost" disabled={!dirty||btnBusy} onClick={()=>void act('正在保存',async()=>{await save();await refresh();setNotice('修改已保存');})}><Save size={15}/>{dirty?'保存修改':'已保存'}</button><button className="button primary" disabled={btnBusy||rendering} onClick={()=>void render()}><Film size={16}/>{rendering?'正在渲染':'制作成品包'}<ArrowRight size={15}/></button></div></div>
     <div className={`engine-info ${project.decision.engine==='jev'?'live':''}`}><Sparkles size={15}/><span>{project.decision.message}</span>{project.decision.confidence!==null&&<b>置信度 {Math.round(project.decision.confidence*100)}%</b>}</div>
     <div className="storyboard-grid"><div className="preview-shell"><div className={`scene-preview ratio-${project.brief.ratio.replace(':','-')}`}>{activeScene&&<img key={`${activeScene.id}-${project.revision}`} src={shotUrl(project,activeScene)} alt={`分镜预览：${activeScene.caption}`}/>}<span className="preview-badge">分镜预览 {String(selected+1).padStart(2,'0')} / {scenes.length}</span>{dirty&&<span className="unsaved">保存后更新画面</span>}</div><div className="playback"><button className="play-control" aria-label={isPlaying?'暂停预览':'播放分镜'} onClick={()=>setIsPlaying(!isPlaying)}>{isPlaying?<span className="pause">Ⅱ</span>:<Play size={18} fill="currentColor"/>}</button><span>{String(scenes.slice(0,selected).reduce((n,s)=>n+s.duration,0)).padStart(2,'0')}s</span><div className="playback-track">{scenes.map((s,i)=><button aria-label={`预览镜头 ${i+1}`} className={i===selected?'active':''} key={s.id} style={{flex:s.duration}} onClick={()=>setSelected(i)}/>)}</div><span>{duration(scenes)}s</span><span className="preview-ratio"><Maximize size={13}/>{project.brief.ratio}</span></div></div>
      <section className="panel scene-editor"><div className="section-top"><div><span className="section-index">SHOT {String(selected+1).padStart(2,'0')}</span><h2>打磨这个镜头</h2></div><span className="chip">可编辑</span></div>{activeScene&&<><label className="field"><span>镜头名称</span><input maxLength={60} value={activeScene.title} onChange={e=>updateScene({title:e.target.value})}/></label><label className="field"><span>画面文案 / 字幕</span><textarea maxLength={160} rows={3} value={activeScene.caption} onChange={e=>updateScene({caption:e.target.value})}/></label><label className="field"><span>镜头说明</span><textarea maxLength={400} rows={3} value={activeScene.direction} onChange={e=>updateScene({direction:e.target.value})}/></label><label className="field duration-field"><span><Clock3 size={14}/>停留时长</span><div><input type="number" min={1} max={30} step={.5} value={activeScene.duration} onChange={e=>updateScene({duration:Number(e.target.value)})}/><span>秒</span></div></label><div className="asset-area"><div><b>镜头素材</b><span>JPG / PNG / WebP · 最大 12 MB</span></div><button className="upload-button" disabled={btnBusy} onClick={()=>uploadRef.current?.click()}><ImagePlus size={20}/><span>{busy==='正在保存素材'?'正在上传…':'上传并替换当前镜头图片'}</span><Plus size={16}/></button>{project.assets.length>0&&<div className="asset-thumbs">{project.assets.map(a=><button key={a.id} onClick={()=>updateScene({assetId:a.id})} className={a.id===activeScene.assetId?'selected':''} title={a.name} aria-label={`使用素材 ${a.name}`}><img src={a.url} alt={a.name}/>{a.id===activeScene.assetId&&<Check size={12}/>}</button>)}<button className={`illustration-option ${activeScene.assetId===null?'selected':''}`} onClick={()=>updateScene({assetId:null})}>示意<br/>画面</button></div>}</div></>}
      <input ref={uploadRef} type="file" accept="image/jpeg,image/png,image/webp" hidden onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file);e.target.value='';}}/></section></div>
     <div className="filmstrip">{scenes.map((s,i)=><button key={s.id} className={`shot-card ${selected===i?'selected':''}`} onClick={()=>{setSelected(i);setIsPlaying(false);}}><div><img src={shotUrl(project,s)} alt={`镜头 ${i+1}`}/><span>{s.duration}s</span></div><b>{s.title}</b><small>{s.caption}</small></button>)}</div><div className="board-footnote"><CheckCheck size={15}/>项目保存在本地。保存修改后，预览画面与导出文件会同步更新。</div>
    </>}
    {stage==='delivery'&&project&&<>
      <div className="delivery-grid"><section className="delivery-hero"><span className="eyebrow">MADE TO BE SHARED</span><h2>{job?.status==='complete'?'你的下一支短片，准备好了。':rendering?'正在把想法，变成作品。':'离作品完成，只差最后一步。'}</h2><p>{job?.status==='complete'?'视频、封面、字幕与制作脚本，已经整理成一个成品包。':'基于已保存的镜头，制作真实 MP4 和配套素材。'}</p><div className="delivery-screen">{job?.status==='complete'&&job.videoUrl?<video key={job.id} controls playsInline preload="metadata" poster={job.coverUrl} src={job.videoUrl}/>:<><img src={shotUrl(project,project.scenes[0]!)} alt="视频首帧预览"/><div className="render-overlay">{rendering?<LoaderCircle size={36} className="spin"/>:<Film size={36}/>}<b>{job?.stage||'等待制作'}</b>{rendering&&<span>已制作 {job.completedScenes} / {job.totalScenes} 个镜头 · 编码完成后自动显示</span>}{job?.status==='failed'&&<span>{job.error}</span>}</div></>}</div><p className="honest-note">MP4 为带字幕和轻微推近动效的图片短片，无配音。镜头脚本可用于后续拍摄或接入视频生成服务。</p></section>
      <section className="panel delivery-panel"><div className="section-top"><h2>你的成品包</h2><span className="chip">{project.brief.ratio}</span></div><p className="section-copy">一套素材，承接你的下一步创作。</p><div className="deliverable-list">{[['MP4 短片','H.264 · 24 fps · 图片动效预览',Film],['首帧封面','JPG 图片 + 可编辑 SVG 底稿',ImagePlus],['字幕与脚本','SRT 字幕 + Markdown 镜头脚本',Clapperboard],['项目与分镜','JSON 项目 + 每镜 JPG 画面',Layers3]].map(([name,desc,Icon],i)=><div key={i}><span className="file-icon">{typeof Icon!=='string'&&<Icon size={20}/>}</span><span><b>{String(name)}</b><small>{String(desc)}</small></span>{job?.status==='complete'?<Check size={15}/>:<span className="file-wait">—</span>}</div>)}</div>
       {job?.status==='complete'?<><a className="button primary full" href={job.packageUrl} download><ArrowDownToLine size={17}/>下载完整成品包<ArrowRight size={16}/></a><a className="button ghost full" href={job.videoUrl} download="xtasy-film.mp4"><Film size={16}/>单独下载视频</a>{job.revision!==project.revision&&<p className="version-note">这份成品基于较早的项目版本。重新制作可包含最新修改。</p>}</>:<button className="button primary full" disabled={btnBusy||rendering} onClick={()=>void render()}>{rendering?<LoaderCircle className="spin" size={17}/>:<Film size={17}/>} {rendering?'正在制作成品包':'开始制作成品包'}</button>}
       <div className="quick-downloads"><span>随时下载制作文件</span><div><a href={`/api/projects/${project.id}/download/script`}>镜头脚本 ↗</a><a href={`/api/projects/${project.id}/download/subtitles`}>SRT 字幕 ↗</a><a href={`/api/projects/${project.id}/download/project`}>项目 JSON ↗</a></div></div><button className="text-button" onClick={()=>setStage('storyboard')}><ArrowLeft size={14}/>回到分镜继续编辑</button>
      </section></div>{exports.length>0&&<section className="export-history"><h3>导出记录</h3>{exports.slice(0,5).map(item=><button key={item.id} onClick={()=>void act('正在读取成品',async()=>setJob(await api<RenderJob>(`/api/jobs/${item.id}`)))}><span>版本 {item.revision} · {formatDate(item.createdAt)}</span><span>{(job?.id===item.id?job.status:item.status)==='complete'?'查看成品':(job?.id===item.id?job.status:item.status)==='failed'?'查看失败原因':'查看任务'}<ArrowRight size={14}/></span></button>)}</section>}
    </>}
   </>}
   {view==='projects'&&<><div className="page-heading"><div><div className="eyebrow">THE WORK YOU MAKE</div><h1>我的项目</h1><p>每一个想法，都值得继续打磨。</p></div><button className="button primary" onClick={newProject}><Plus size={16}/>新建项目</button></div><div className="project-search"><input aria-label="搜索项目" placeholder="搜索项目名称…" value={search} onChange={e=>setSearch(e.target.value)}/><span>{projects.length} 个项目 · 本地持久保存</span></div>{projects.length===0?<div className="empty-state"><FolderOpen size={44}/><h2>你的第一支短片，从这里开始。</h2><p>用一份简报，创建第一个项目。</p><button className="button primary" onClick={newProject}>开始创作<ArrowRight size={16}/></button></div>:<div className="project-grid">{projects.filter(p=>p.name.toLowerCase().includes(search.toLowerCase())).map((p,i)=><button className="project-card" key={p.id} disabled={btnBusy} onClick={()=>void openProject(p.id)}><div className={`project-cover project-color-${i%3}`}><span>XTASY DIRECTOR / PROJECT</span><b>{p.name}</b><span>{p.ratio} · {p.sceneCount} 个镜头</span><ArrowRight size={24}/></div><div><b>{p.name}</b><small>{formatDate(p.updatedAt)} 更新<ArrowRight size={14}/></small></div></button>)}</div>}</>}
   {view==='templates'&&<><div className="page-heading"><div><div className="eyebrow">A GOOD PLACE TO START</div><h1>为你的故事，找到一种表达。</h1><p>三个经过设计的内容结构，覆盖产品、卖点与日常故事。</p></div><span className="big-asterisk">✳</span></div><div className="template-library">{templates.map((t,i)=><section className="panel" key={t.id}><div className={`library-art art-${i}`}><span>{t.english}</span><span className="abstract-circle"/><span className="abstract-block"/><b>0{i+1}</b></div><div className="library-copy"><span className="eyebrow">{t.tag}</span><h2>{t.name}</h2><p>{t.description}</p><div className="template-structure">{i===0?'第一眼 → 触感 → 细节 → 日常 → 留白':i===1?'需求 → 核心价值 → 产品细节 → 场景 → 行动':'开场 → 相遇 → 细节 → 日常 → 余韵'}</div><button className="button primary full" onClick={()=>selectTemplate(t.id)}>使用这个模板<ArrowRight size={16}/></button></div></section>)}</div></>}
   {view==='settings'&&<><div className="page-heading"><div><div className="eyebrow">YOUR STUDIO, YOUR WAY</div><h1>工作室设置</h1><p>创作数据与 API 密钥保留在运行应用的机器上。</p></div></div><section className="panel settings-panel"><div><Sparkles size={24}/><h2>Jev 内容判断</h2><span className="chip">{health?.jevConfigured?'已配置':'未配置'}</span></div><p>Jev 根据受众、卖点和表达风格选择内容模板。它不生成视频或台词；程序负责组装镜头，FFmpeg 负责制作视频。服务无法连接或判断不明确时，会清楚提示并回退到本地模板。</p><p>在仓库根目录的 <code>.env</code> 中设置 <code>TYPESAFE_API_KEY</code> 后重启服务。密钥仅由服务器读取，浏览器不会接收密钥。</p><hr/><div><Film size={24}/><h2>本地视频制作</h2><span className="chip">{health?.ffmpeg?'FFmpeg 可用':'需要安装 FFmpeg'}</span></div><p>支持 16:9、9:16 和 1:1。包含图片推近动效、内嵌字幕、封面和标准 SRT；当前版本不提供自动配音。未安装 FFmpeg 时，仍然可以下载镜头脚本和字幕。</p><hr/><div><FolderOpen size={24}/><h2>本地项目存储</h2><span className="chip">自动保存项目</span></div><p>新项目和上传素材会写入本机 <code>.local/</code>。镜头修改通过“保存修改”写入，导出时会先保存。项目库在重启服务后仍可使用。此版本适用于本机单人工作室；不包含账户、支付或多人权限。</p><button className="button ghost" onClick={()=>void act('正在检查',async()=>{setHealth(await api<Health>('/api/health'));setNotice('工作室状态已刷新');})}>刷新运行状态</button></section></>}
   <footer className="page-footer"><span>XTASY DIRECTOR</span><span>从灵感，到下一帧。</span><span>CRAFTED FOR CREATORS</span></footer>
   </main>
  </div>
 </div>{btnBusy&&<div className="operation-status" role="status" aria-live="polite"><LoaderCircle size={16} className="spin"/>{busy}，请稍候…</div>}</>;
}
function ArrowUpRight(){return <svg width="14" height="14" viewBox="0 0 14 14" fill="none" aria-hidden="true"><path d="M3 11L11 3M3 3H11V11" stroke="currentColor" strokeWidth="1.4"/></svg>;}
